### ISSUE TITLE
compilation errors with TypeScript 4.3 and noImplicitOverride

### ISSUE THREAD

**Issue by quezak** [dethcrypto/TypeChain#393]
TS 4.3 adds a `noImplicitOverride` compilation flag, and all methods that override a parent method are required to be marked with `override`.

@krzkaczor how should we handle this? Add a switch or detect TS version and include the override modifiers?
I don't think there is an option to disable `noImplicitOverride` selectively for the typechain-generated directories :(

Other ideas seem very ugly since they effectively disable typechecking:
* `// @ts-nocheck` at the top of the file
* `// @ts-ignore` at each meathod

**Comment by krzkaczor** [comment]
> @krzkaczor how should we handle this? Add a switch or detect TS version and include the override modifiers?

I like this solution. But for sure this requires improvements to our CI pipeline to ensure that it works with TS 4.3 and with previous versions.

**Comment by microHoffman** [comment]
Hello, any updates on this one?:)

**Comment by krzkaczor** [comment]
Related: https://github.com/dethcrypto/TypeChain/pull/543

**Comment by microHoffman** [comment]
@krzkaczor Hello, i've just tried to re-enable the `noImplicitOverride` flag in `tsconfig.json` and re-generated typings with Typechain 6.0.4 (also tried 5.2.0), but it still did not generated the classes with the `override` keywords where is it needed.

I'm wondering if I am missing something, or this has not yet been resolved? I know that I can exclude the directory from the ts checking. The only downside to this is that in order to exclude the generated files, I would need to change my folder structure for that, as if I am not mistaken I can not exclude files/folders that I already have listed in `tsconfig.json` (even with wildcard characters usage). 

This is not a big problem for me, so im just asking for the info. Thanks for your time and help, I appreciate it!:)

**Comment by hasparus** [comment]
Hey @krzkaczor, I believe this wasn't shipped yet.

**Comment by krzkaczor** [comment]
Yeah right. This was not implemented at all. Releated: https://github.com/dethcrypto/TypeChain/issues/546
